// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.34.1
// 	protoc        v5.29.3
// source: inventory_service/proto/inventory.proto

package proto

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Inventory struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id       string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	StockKey string `protobuf:"bytes,5,opt,name=stock_key,json=stockKey,proto3" json:"stock_key,omitempty"`
	Count    int64  `protobuf:"varint,6,opt,name=count,proto3" json:"count,omitempty"`
}

func (x *Inventory) Reset() {
	*x = Inventory{}
	if protoimpl.UnsafeEnabled {
		mi := &file_inventory_service_proto_inventory_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Inventory) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Inventory) ProtoMessage() {}

func (x *Inventory) ProtoReflect() protoreflect.Message {
	mi := &file_inventory_service_proto_inventory_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Inventory.ProtoReflect.Descriptor instead.
func (*Inventory) Descriptor() ([]byte, []int) {
	return file_inventory_service_proto_inventory_proto_rawDescGZIP(), []int{0}
}

func (x *Inventory) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Inventory) GetStockKey() string {
	if x != nil {
		return x.StockKey
	}
	return ""
}

func (x *Inventory) GetCount() int64 {
	if x != nil {
		return x.Count
	}
	return 0
}

type GetInventoryReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *GetInventoryReq) Reset() {
	*x = GetInventoryReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_inventory_service_proto_inventory_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetInventoryReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetInventoryReq) ProtoMessage() {}

func (x *GetInventoryReq) ProtoReflect() protoreflect.Message {
	mi := &file_inventory_service_proto_inventory_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetInventoryReq.ProtoReflect.Descriptor instead.
func (*GetInventoryReq) Descriptor() ([]byte, []int) {
	return file_inventory_service_proto_inventory_proto_rawDescGZIP(), []int{1}
}

func (x *GetInventoryReq) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type GetInventoryResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Inventory *Inventory `protobuf:"bytes,1,opt,name=inventory,proto3" json:"inventory,omitempty"`
}

func (x *GetInventoryResp) Reset() {
	*x = GetInventoryResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_inventory_service_proto_inventory_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetInventoryResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetInventoryResp) ProtoMessage() {}

func (x *GetInventoryResp) ProtoReflect() protoreflect.Message {
	mi := &file_inventory_service_proto_inventory_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetInventoryResp.ProtoReflect.Descriptor instead.
func (*GetInventoryResp) Descriptor() ([]byte, []int) {
	return file_inventory_service_proto_inventory_proto_rawDescGZIP(), []int{2}
}

func (x *GetInventoryResp) GetInventory() *Inventory {
	if x != nil {
		return x.Inventory
	}
	return nil
}

type GetInventoriesReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Page  int64 `protobuf:"varint,1,opt,name=page,proto3" json:"page,omitempty"`
	Limit int64 `protobuf:"varint,2,opt,name=limit,proto3" json:"limit,omitempty"`
}

func (x *GetInventoriesReq) Reset() {
	*x = GetInventoriesReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_inventory_service_proto_inventory_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetInventoriesReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetInventoriesReq) ProtoMessage() {}

func (x *GetInventoriesReq) ProtoReflect() protoreflect.Message {
	mi := &file_inventory_service_proto_inventory_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetInventoriesReq.ProtoReflect.Descriptor instead.
func (*GetInventoriesReq) Descriptor() ([]byte, []int) {
	return file_inventory_service_proto_inventory_proto_rawDescGZIP(), []int{3}
}

func (x *GetInventoriesReq) GetPage() int64 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *GetInventoriesReq) GetLimit() int64 {
	if x != nil {
		return x.Limit
	}
	return 0
}

type GetInventoriesResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Inventories []*Inventory `protobuf:"bytes,1,rep,name=inventories,proto3" json:"inventories,omitempty"`
	Count       int64        `protobuf:"varint,2,opt,name=count,proto3" json:"count,omitempty"`
	Page        int64        `protobuf:"varint,3,opt,name=page,proto3" json:"page,omitempty"`
	Limit       int64        `protobuf:"varint,4,opt,name=limit,proto3" json:"limit,omitempty"`
}

func (x *GetInventoriesResp) Reset() {
	*x = GetInventoriesResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_inventory_service_proto_inventory_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetInventoriesResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetInventoriesResp) ProtoMessage() {}

func (x *GetInventoriesResp) ProtoReflect() protoreflect.Message {
	mi := &file_inventory_service_proto_inventory_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetInventoriesResp.ProtoReflect.Descriptor instead.
func (*GetInventoriesResp) Descriptor() ([]byte, []int) {
	return file_inventory_service_proto_inventory_proto_rawDescGZIP(), []int{4}
}

func (x *GetInventoriesResp) GetInventories() []*Inventory {
	if x != nil {
		return x.Inventories
	}
	return nil
}

func (x *GetInventoriesResp) GetCount() int64 {
	if x != nil {
		return x.Count
	}
	return 0
}

func (x *GetInventoriesResp) GetPage() int64 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *GetInventoriesResp) GetLimit() int64 {
	if x != nil {
		return x.Limit
	}
	return 0
}

var File_inventory_service_proto_inventory_proto protoreflect.FileDescriptor

var file_inventory_service_proto_inventory_proto_rawDesc = []byte{
	0x0a, 0x27, 0x69, 0x6e, 0x76, 0x65, 0x6e, 0x74, 0x6f, 0x72, 0x79, 0x5f, 0x73, 0x65, 0x72, 0x76,
	0x69, 0x63, 0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x69, 0x6e, 0x76, 0x65, 0x6e, 0x74,
	0x6f, 0x72, 0x79, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x1c, 0x67, 0x6f, 0x6f, 0x67, 0x6c,
	0x65, 0x2f, 0x61, 0x70, 0x69, 0x2f, 0x61, 0x6e, 0x6e, 0x6f, 0x74, 0x61, 0x74, 0x69, 0x6f, 0x6e,
	0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x4e, 0x0a, 0x09, 0x49, 0x6e, 0x76, 0x65, 0x6e,
	0x74, 0x6f, 0x72, 0x79, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x02, 0x69, 0x64, 0x12, 0x1b, 0x0a, 0x09, 0x73, 0x74, 0x6f, 0x63, 0x6b, 0x5f, 0x6b, 0x65,
	0x79, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x73, 0x74, 0x6f, 0x63, 0x6b, 0x4b, 0x65,
	0x79, 0x12, 0x14, 0x0a, 0x05, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x18, 0x06, 0x20, 0x01, 0x28, 0x03,
	0x52, 0x05, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x22, 0x21, 0x0a, 0x0f, 0x47, 0x65, 0x74, 0x49, 0x6e,
	0x76, 0x65, 0x6e, 0x74, 0x6f, 0x72, 0x79, 0x52, 0x65, 0x71, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x22, 0x3c, 0x0a, 0x10, 0x47, 0x65,
	0x74, 0x49, 0x6e, 0x76, 0x65, 0x6e, 0x74, 0x6f, 0x72, 0x79, 0x52, 0x65, 0x73, 0x70, 0x12, 0x28,
	0x0a, 0x09, 0x69, 0x6e, 0x76, 0x65, 0x6e, 0x74, 0x6f, 0x72, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x0a, 0x2e, 0x49, 0x6e, 0x76, 0x65, 0x6e, 0x74, 0x6f, 0x72, 0x79, 0x52, 0x09, 0x69,
	0x6e, 0x76, 0x65, 0x6e, 0x74, 0x6f, 0x72, 0x79, 0x22, 0x3d, 0x0a, 0x11, 0x47, 0x65, 0x74, 0x49,
	0x6e, 0x76, 0x65, 0x6e, 0x74, 0x6f, 0x72, 0x69, 0x65, 0x73, 0x52, 0x65, 0x71, 0x12, 0x12, 0x0a,
	0x04, 0x70, 0x61, 0x67, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x04, 0x70, 0x61, 0x67,
	0x65, 0x12, 0x14, 0x0a, 0x05, 0x6c, 0x69, 0x6d, 0x69, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03,
	0x52, 0x05, 0x6c, 0x69, 0x6d, 0x69, 0x74, 0x22, 0x82, 0x01, 0x0a, 0x12, 0x47, 0x65, 0x74, 0x49,
	0x6e, 0x76, 0x65, 0x6e, 0x74, 0x6f, 0x72, 0x69, 0x65, 0x73, 0x52, 0x65, 0x73, 0x70, 0x12, 0x2c,
	0x0a, 0x0b, 0x69, 0x6e, 0x76, 0x65, 0x6e, 0x74, 0x6f, 0x72, 0x69, 0x65, 0x73, 0x18, 0x01, 0x20,
	0x03, 0x28, 0x0b, 0x32, 0x0a, 0x2e, 0x49, 0x6e, 0x76, 0x65, 0x6e, 0x74, 0x6f, 0x72, 0x79, 0x52,
	0x0b, 0x69, 0x6e, 0x76, 0x65, 0x6e, 0x74, 0x6f, 0x72, 0x69, 0x65, 0x73, 0x12, 0x14, 0x0a, 0x05,
	0x63, 0x6f, 0x75, 0x6e, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x05, 0x63, 0x6f, 0x75,
	0x6e, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x70, 0x61, 0x67, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x03,
	0x52, 0x04, 0x70, 0x61, 0x67, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x6c, 0x69, 0x6d, 0x69, 0x74, 0x18,
	0x04, 0x20, 0x01, 0x28, 0x03, 0x52, 0x05, 0x6c, 0x69, 0x6d, 0x69, 0x74, 0x32, 0xb5, 0x01, 0x0a,
	0x10, 0x49, 0x6e, 0x76, 0x65, 0x6e, 0x74, 0x6f, 0x72, 0x79, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63,
	0x65, 0x12, 0x4f, 0x0a, 0x0c, 0x47, 0x65, 0x74, 0x49, 0x6e, 0x76, 0x65, 0x6e, 0x74, 0x6f, 0x72,
	0x79, 0x12, 0x10, 0x2e, 0x47, 0x65, 0x74, 0x49, 0x6e, 0x76, 0x65, 0x6e, 0x74, 0x6f, 0x72, 0x79,
	0x52, 0x65, 0x71, 0x1a, 0x11, 0x2e, 0x47, 0x65, 0x74, 0x49, 0x6e, 0x76, 0x65, 0x6e, 0x74, 0x6f,
	0x72, 0x79, 0x52, 0x65, 0x73, 0x70, 0x22, 0x1a, 0x82, 0xd3, 0xe4, 0x93, 0x02, 0x14, 0x12, 0x12,
	0x2f, 0x76, 0x31, 0x2f, 0x69, 0x6e, 0x76, 0x65, 0x6e, 0x74, 0x6f, 0x72, 0x79, 0x2f, 0x7b, 0x69,
	0x64, 0x7d, 0x12, 0x50, 0x0a, 0x0e, 0x47, 0x65, 0x74, 0x49, 0x6e, 0x76, 0x65, 0x6e, 0x74, 0x6f,
	0x72, 0x69, 0x65, 0x73, 0x12, 0x12, 0x2e, 0x47, 0x65, 0x74, 0x49, 0x6e, 0x76, 0x65, 0x6e, 0x74,
	0x6f, 0x72, 0x69, 0x65, 0x73, 0x52, 0x65, 0x71, 0x1a, 0x13, 0x2e, 0x47, 0x65, 0x74, 0x49, 0x6e,
	0x76, 0x65, 0x6e, 0x74, 0x6f, 0x72, 0x69, 0x65, 0x73, 0x52, 0x65, 0x73, 0x70, 0x22, 0x15, 0x82,
	0xd3, 0xe4, 0x93, 0x02, 0x0f, 0x12, 0x0d, 0x2f, 0x76, 0x31, 0x2f, 0x69, 0x6e, 0x76, 0x65, 0x6e,
	0x74, 0x6f, 0x72, 0x79, 0x42, 0x42, 0x5a, 0x40, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63,
	0x6f, 0x6d, 0x2f, 0x41, 0x79, 0x61, 0x6e, 0x6f, 0x6b, 0x6f, 0x6a, 0x69, 0x4b, 0x69, 0x79, 0x6f,
	0x74, 0x61, 0x6b, 0x61, 0x38, 0x2f, 0x45, 0x2d, 0x43, 0x6f, 0x6d, 0x6d, 0x65, 0x72, 0x63, 0x65,
	0x2f, 0x69, 0x6e, 0x76, 0x65, 0x6e, 0x74, 0x6f, 0x72, 0x79, 0x5f, 0x73, 0x65, 0x72, 0x76, 0x69,
	0x63, 0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_inventory_service_proto_inventory_proto_rawDescOnce sync.Once
	file_inventory_service_proto_inventory_proto_rawDescData = file_inventory_service_proto_inventory_proto_rawDesc
)

func file_inventory_service_proto_inventory_proto_rawDescGZIP() []byte {
	file_inventory_service_proto_inventory_proto_rawDescOnce.Do(func() {
		file_inventory_service_proto_inventory_proto_rawDescData = protoimpl.X.CompressGZIP(file_inventory_service_proto_inventory_proto_rawDescData)
	})
	return file_inventory_service_proto_inventory_proto_rawDescData
}

var file_inventory_service_proto_inventory_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_inventory_service_proto_inventory_proto_goTypes = []interface{}{
	(*Inventory)(nil),          // 0: Inventory
	(*GetInventoryReq)(nil),    // 1: GetInventoryReq
	(*GetInventoryResp)(nil),   // 2: GetInventoryResp
	(*GetInventoriesReq)(nil),  // 3: GetInventoriesReq
	(*GetInventoriesResp)(nil), // 4: GetInventoriesResp
}
var file_inventory_service_proto_inventory_proto_depIdxs = []int32{
	0, // 0: GetInventoryResp.inventory:type_name -> Inventory
	0, // 1: GetInventoriesResp.inventories:type_name -> Inventory
	1, // 2: InventoryService.GetInventory:input_type -> GetInventoryReq
	3, // 3: InventoryService.GetInventories:input_type -> GetInventoriesReq
	2, // 4: InventoryService.GetInventory:output_type -> GetInventoryResp
	4, // 5: InventoryService.GetInventories:output_type -> GetInventoriesResp
	4, // [4:6] is the sub-list for method output_type
	2, // [2:4] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_inventory_service_proto_inventory_proto_init() }
func file_inventory_service_proto_inventory_proto_init() {
	if File_inventory_service_proto_inventory_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_inventory_service_proto_inventory_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Inventory); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_inventory_service_proto_inventory_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetInventoryReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_inventory_service_proto_inventory_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetInventoryResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_inventory_service_proto_inventory_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetInventoriesReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_inventory_service_proto_inventory_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetInventoriesResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_inventory_service_proto_inventory_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_inventory_service_proto_inventory_proto_goTypes,
		DependencyIndexes: file_inventory_service_proto_inventory_proto_depIdxs,
		MessageInfos:      file_inventory_service_proto_inventory_proto_msgTypes,
	}.Build()
	File_inventory_service_proto_inventory_proto = out.File
	file_inventory_service_proto_inventory_proto_rawDesc = nil
	file_inventory_service_proto_inventory_proto_goTypes = nil
	file_inventory_service_proto_inventory_proto_depIdxs = nil
}
